# Generated by Django 5.1 on 2024-08-13 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Airecipe', '0004_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlistitem',
            name='items',
            field=models.CharField(max_length=255),
        ),
    ]
